### PR TITLE
Recursively get parameters from SSM

### PR DESCRIPTION
**Pull request by SmallNic**
Once I added an 11th param to our param store in SSM, I noticed we were only getting 10 results back. The [AWS SDK docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ssm/classes/getparametersbypathcommand.html#input) revealed that we could set the max number of results to increase the results or take advantage of the `NextToken`

> If the service reaches an internal limit while processing the results, it stops the operation and returns the matching values up to that point and a NextToken. You can specify the NextToken in a subsequent call to get the next set of results.

I updated the code so that `getParametersByPath` calls itself again if the `NextToken` output tells us there are more params to be fetched.

### CODE REVIEW

**Comment by rkit** [comment]
Thank you! I'll release this update in about a week.

**Comment by SmallNic** [comment]
Much appreciated @rkit !

**Comment by SmallNic** [comment]
Hey @rkit, wanted to check in again and see if you know when you'll have time to check this out for us?

**Comment by rkit** [comment]
Done. Thank you 👍

**Pull request merged**
